### ISSUE TITLE
Request: If a user is currently viewing a resource's detail page, or resource's relationships detail page

### ISSUE THREAD

**Issue by tdevaney07** [mateusz-peczkowski/nova-heartbeat-resource-field#1]
Would be great to add the same functionality on the detail page of a resource, and also have it show if say, the user is browsing the resource's relationships as well.

**Comment by mateusz-peczkowski** [comment]
@tdevaney07 hey. I'm sorry for not getting back to you sooner. Can you explain more about what you want to present on the details page? I implemented there something like that
<img width="836" alt="image" src="https://github.com/user-attachments/assets/7e888a34-a3f5-49bd-b592-1103c8810764">

Is this not visible on your admin panel? OR do you want to block details when the user interacts with it?
With second thing will be a little bit harder, but of course possible, this was not included by purpose in my plugin as I just need to block "editing" the same resource by two people, and on details I have as above option to retake the resource... So it is doable but as a feature improvement with some options to enable/disable something like that.

Maybe give me your usage example which will give me more idea of "why" ;)
